name: PR Branch Name Check

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        id: check_branch
        run: |
          echo "Branch name is ${{ github.head_ref }}"
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" =~ ^((maqeel|psilva|gchawda|tcarter)/(dev|bug|fix)/.+|staging-[0-9]{1,2}/[0-9]{1,2}/[0-9]{4})$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.B_GITHUB_TOKEN }}
          script: |
            const isValid = '${{ steps.check_branch.outputs.valid }}' === 'true';
            const message = isValid
              ? '✅ **Branch name is valid.**'
              : '❌ **Branch name is invalid.**\n\nBranch names should follow either:\n1. Format: `{user}/{branch_type}/{feature_name}`\n   - **User** must be one of: `maqeel`, `psilva`, `gchawda`, `tcarter`\n   - **Branch type** must be one of: `dev`, `bug`, `fix`\n   - **Feature name** is required and can be any valid string\n2. Format: `staging-MM/DD/YYYY`';
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
